export const REQ_RERENDER = 'REQ_RE_RENDER';
export const FETCH_POST = 'FETCH_POST';
export const SAVE_POST_DATA = 'SAVE_POST_DATA';
export const FAILED_TO_FETCH_POST = 'FAILED_TO_FETCH_POST';
export const SEARCH_IN_POST = 'SEARCH_IN_POST';
